### ISSUE TITLE
License files missing?

### ISSUE THREAD

**Issue by Hedda** [kenji123/pvr.stalker.client#1]
@kenji123 Cool addon for Kodi! It does however look like your source code is missing license files?

I would recommend open source your addon as LGPLv2 or GPLv2, alternatively LGPLv2 or GPLv2.

**Comment by kenji123** [comment]
Your right. It's GPLv2. Same as the other Kodi PVR addons. Some of the source files have the license headers already. Just need to add the license file and a couple others like the changelog and readme.
